export { ActivityIcon } from './ActivityIcon'
export { CloseIcon } from './CloseIcon'
export { MenuIcon } from './MenuIcon'
export { PauseIcon } from './PauseIcon'
export { PlayIcon } from './PlayIcon'
export { PersonIcon } from './PersonIcon'
export { WhatsAppIcon } from './WhatsAppIcon'
